#!/usr/bin/perl -w
#
#  Input file fb-map-latlong should be using the Bessel 1841 ellipsoid
#  (which is what the Austrian datum uses).
#

open SVX, ">fb-map.svx" or die $!;
open COORDS, "<fb-map-latlong.txt" or die $!;
print SVX "; This file is auto-generated by make-fb-map.pl: do not edit.\n\n";
while (<COORDS>) {
    chomp;
    my ($name, $coords) = $_ =~ /(\S*)\s*(.*)/;
    $result = "*fix fbmap_$name reference\t" . `lltoutm austria $coords`;
    print SVX $result;
}
close SVX;
close COORDS;


#####################################
# replaced with a single run of this python code due to new *cs command in survex

ls = open("/home/julian/data/expodata/loser/fixedpts/fb-map-latlong.txt").readlines()
lo = open("/home/julian/data/expodata/loser/fixedpts/fb-map.svx", "w")
lo.write("*begin\n*cs long-lat\n")
for l in ls:
    if l.strip():
        n, a1, a2, a3, b1, b2, b3, alt = l.split()
        lat = float(a1)+float(a2)/60+float(a3)/3600
        lng = float(b1)+float(b2)/60+float(b3)/3600
        lo.write("*fix fbmap_%s reference %.6f %.6f %s\n" % (n, lng, lat, alt))
lo.write("*end\n")
lo.close()




