#!/bin/bash

set -eu -o pipefail

if [ "$(hg st -q)" != "" ]; then
  # Insist repo is clean so that if something goes wrong during generation
  # it's easy to revert.
  echo "Repository is not clean.  Commit or revert changes as desired then"
  echo "re-run this script."
  exit 1
fi

root=$(hg showconfig | grep mainreporoot | sed 's/[^=]*=//')

cd $root/gpx

echo "; Automatically generated by make_svx.sh, do not edit." > all_gpx.svx
echo >> all_gpx.svx

for year in 20??; do
  mkdir -p $year/svx
  all_gpx=$year/svx/all_gpx.svx

  echo "; Automatically generated by make_svx.sh, do not edit." > $all_gpx
  echo >> $all_gpx

  for gpx in $year/*.gpx; do
    gpx2survex.exe -svx-time-zone Europe/Vienna -output-dir $year/svx $gpx
    echo "*include $(basename $gpx | sed 's/\.gpx$//')" >> $all_gpx
  done

  echo "*include $year/svx/all_gpx.svx" >> all_gpx.svx
  echo "*include $year/additional_info.svx" >> all_gpx.svx
done
